set search_path to tickets4u;INSERT INTO filme values(17, 'Star Wars: Episode VII - The Force Awakens', 'Three decades after the Empires defeat, a new threat arises in the militant First Order. Stormtrooper defector Finn and spare parts scavenger Rey are caught up in the Resistances search for the missing Luke Skywalker.', 'Action','True','136', 'J.J. Abrams', 'Cinecolor Films', '4d', 'Lucasfilm');
INSERT INTO filme values(18, 'Thor: Ragnarok', 'Imprisoned, the almighty Thor finds himself in a lethal gladiatorial contest against the Hulk, his former ally. Thor must fight for survival and race against time to prevent the all-powerful Hela from destroying his home and the Asgardian civilization.', 'Action','False','130', 'Taika Waititi', 'Cinecolor Films', '3d', 'Marvel Entertainment');
INSERT INTO filme values(19, 'Metropolis', 'In a futuristic city sharply divided between the working class and the city planners, the son of the citys mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.', 'Drama','False','153', 'Fritz Lang', 'Paramount-Ufa-Metro-Verleihbetriebe GmbH (Parufamet)', 'normal', 'Universum Film');
INSERT INTO filme values(25, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'An insane general triggers a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.', 'Comedy','True','95', 'Stanley Kubrick', 'Columbia Pictures', 'normal', 'Columbia Pictures Corporation');
INSERT INTO filme values(26, 'The Grand Budapest Hotel', 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', 'Adventure','True','99', 'Wes Anderson', '20th Century Fox', 'normal', 'Fox Searchlight Pictures');
INSERT INTO filme values(27, 'Faa yeung nin wa', 'Two neighbors, a woman and a man, form a strong bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit similar wrongs.', 'Drama','False','98', 'Kar-Wai Wong', 'Artistas Argentinos Asociados (AAA)', 'normal', 'Block 2 Pictures');
INSERT INTO filme values(28, 'Sunrise: A Song of Two Humans', 'An allegorical tale about a man fighting the good and evil within him. Both sides are made flesh - one a sophisticated woman he is attracted to and the other his wife.', 'Drama','False','94', 'F.W. Murnau', 'Fox Film Corporation', '4d', 'Fox Film Corporation');
INSERT INTO filme values(29, 'Cera una volta il West', 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.', 'Western','False','164', 'Sergio Leone', 'Euro International Film (EIA)', 'normal', 'Rafran Cinematografica');
INSERT INTO filme values(30, 'Star Wars', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empires world-destroying battle-station while also attempting to rescue Princess Leia from the evil Darth Vader.', 'Action','True','121', 'George Lucas', 'Twentieth Century Fox', '3d', 'Lucasfilm');
INSERT INTO filme values(31, 'Braveheart', 'When his secret bride is executed for assaulting an English soldier who tried to rape her, Sir William Wallace begins a revolt against King Edward I of England.', 'Biography','True','178', 'Mel Gibson', 'Paramount Pictures', '3d', 'Icon Entertainment International');
INSERT INTO filme values(32, 'Lawrence of Arabia', 'The story of , the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.', 'Adventure','True','216', 'David Lean', 'Columbia Pictures', '3d', 'Horizon Pictures (II)');
INSERT INTO filme values(33, 'Trainspotting', 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.', 'Drama','True','94', 'Danny Boyle', 'Intersonic', '4d', 'Channel Four Films');
INSERT INTO filme values(34, 'Pulp Fiction', 'The lives of two mob hit men, a boxer, a gangsters wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Crime','True','154', 'Quentin Tarantino', 'Miramax', '3d', 'Miramax');
INSERT INTO filme values(35, 'The Grapes of Wrath', 'A poor Midwest family is forced off their land. They travel to California, suffering the misfortunes of the homeless in the Great Depression.', 'Drama','True','129', 'John Ford', 'Twentieth Century Fox', '4d', 'Twentieth Century Fox');
INSERT INTO filme values(36, 'Sunrise: A Song of Two Humans', 'An allegorical tale about a man fighting the good and evil within him. Both sides are made flesh - one a sophisticated woman he is attracted to and the other his wife.', 'Drama','False','94', 'F.W. Murnau', 'Fox Film Corporation', '4d', 'Fox Film Corporation');
INSERT INTO filme values(37, 'A Wednesday', 'A retiring police officer reminisces about the most astounding day of his career. About a case that was never filed but continues to haunt him in his memories - the case of a man and a Wednesday.', 'Crime','True','India:104', 'Neeraj Pandey', 'UTV Motion Pictures', '3d', 'Anjum Rizvi Film Company');
INSERT INTO filme values(38, 'Psycho', 'A Phoenix secretary embezzles $40,000 from her employers client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', 'Horror','True','109', 'Alfred Hitchcock', 'Paramount Pictures', '3d', 'Shamley Productions');
INSERT INTO filme values(39, 'The Bourne Ultimatum', 'Jason Bourne dodges a ruthless CIA official and his agents from a new assassination program while searching for the origins of his life as a trained killer.', 'Action','False','115', 'Paul Greengrass', 'Bontonfilm', '4d', 'Universal Pictures');
INSERT INTO filme values(40, 'Heat', 'A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist, while both sides attempt to find balance between their personal and their professional lives.', 'Action','False','170', 'Michael Mann', 'Warner Bros.', '3d', 'Warner Bros.');
INSERT INTO filme values(88, 'Schindlers List', 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.', 'Biography','False','195', 'Steven Spielberg', 'Universal Pictures', 'normal', 'Universal Pictures');
INSERT INTO filme values(89, 'The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Saurons army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'Adventure','True','201', 'Peter Jackson', 'New Line Cinema', '3d', 'New Line Cinema');
INSERT INTO filme values(90, 'Munna Bhai M.B.B.S.', 'A gangster sets out to fulfill his fathers dream of becoming a doctor.', 'Comedy','True','156', 'Rajkumar Hirani', 'EuroVideo', '4d', 'Vinod Chopra Productions');
INSERT INTO filme values(91, 'Paris, Texas', 'Travis Henderson, an aimless drifter who has been missing for four years, wanders out of the desert and must reconnect with society, himself, his life, and his family.', 'Drama','True','145', 'Wim Wenders', 'Argos Films', '4d', 'Road Movies Filmproduktion');
INSERT INTO filme values(92, 'Pulp Fiction', 'The lives of two mob hit men, a boxer, a gangsters wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Crime','False','154', 'Quentin Tarantino', 'Miramax', '4d', 'Miramax');
INSERT INTO filme values(93, 'Snatch', 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 'Comedy','False','104', 'Guy Ritchie', 'Sony Pictures Entertainment (SPE)', '4d', 'Columbia Pictures Corporation');
INSERT INTO filme values(94, 'Gone with the Wind', 'A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods.', 'Drama','True','238', 'Victor Fleming', 'Metro-Goldwyn-Mayer (MGM)', '3d', 'Selznick International Pictures');
INSERT INTO filme values(95, 'Der Untergang', 'Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictators final days in his Berlin bunker at the end of WWII.', 'Biography','True','156', 'Oliver Hirschbiegel', '01 Distribution', '4d', 'Constantin Film');
INSERT INTO filme values(96, 'Dangal', 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.', 'Action','True','161', 'Nitesh Tiwari', 'UTV Motion Pictures', '4d', 'Aamir Khan Productions');
INSERT INTO filme values(97, 'Léon', 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual relationship, as she becomes his protégée and learns the assassins trade.', 'Crime','False','110', 'Luc Besson', 'Gaumont Buena Vista International (GBVI)', 'normal', 'Gaumont');
INSERT INTO filme values(98, 'L.A. Confidential', 'As corruption grows in 1950s LA, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.', 'Crime','True','138', 'Curtis Hanson', 'Gemini Film', 'normal', 'Regency Enterprises');
INSERT INTO filme values(99, 'All About Eve', 'An ingenue insinuates herself into the company of an established but aging stage actress and her circle of theater friends.', 'Drama','False','138', 'Joseph L. Mankiewicz', 'Twentieth Century Fox', 'normal', 'Twentieth Century Fox');
INSERT INTO filme values(100, 'Ben-Hur', 'When a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge.', 'Adventure','True','212', 'William Wyler', 'Metro-Goldwyn-Mayer (MGM)', '3d', 'Metro-Goldwyn-Mayer (MGM)');
INSERT INTO filme values(101, 'Rush', 'The merciless 1970s rivalry between Formula One rivals  and .', 'Action','True','123', 'Ron Howard', 'Film & TV House', 'normal', 'Exclusive Media Group');
INSERT INTO filme values(102, 'Idi i smotri', 'After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.', 'Drama','False','142', 'Elem Klimov', 'Sovexportfilm', '4d', 'Belarusfilm');
INSERT INTO filme values(103, 'Full Metal Jacket', 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.', 'Drama','False','116', 'Stanley Kubrick', 'Warner Bros.', 'normal', 'Natant');
INSERT INTO show Values(7, 'John Williams', 'blues', 'None');
INSERT INTO show Values(8, 'Mark Mothersbaugh', 'blues', 'None');
INSERT INTO show Values(9, 'Gottfried Huppertz', 'jazz', 'None');
INSERT INTO show Values(10, 'Laurie Johnson', 'jazz', 'None');
INSERT INTO show Values(11, 'Alexandre Desplat', 'jazz', 'None');
INSERT INTO show Values(12, 'Michael Galasso', 'pagode', 'None');
INSERT INTO show Values(13, 'R.H. Bassett', 'trilha_sonora', 'None');
INSERT INTO show Values(14, 'Ennio Morricone', 'eletronico', 'None');
INSERT INTO show Values(15, 'John Williams', 'rock', 'None');
INSERT INTO show Values(16, 'James Horner', 'rock', 'None');
INSERT INTO show Values(49, 'Maurice Jarre', 'blues', 'None');
INSERT INTO show Values(50, 'Nao_disponivel', 'samba', 'None');
INSERT INTO esporte Values(52, 'futebol', 'palmeiras X corinthians');
INSERT INTO esporte Values(53, 'futebol', 'sao_paulo X atletico_mineiro');
INSERT INTO esporte Values(54, 'basquete', 'oklahoma X philadelphia');
INSERT INTO esporte Values(55, 'basquete', 'chicago X charlotte');
INSERT INTO esporte Values(56, 'basquete', 'philadelphia X new_york');
INSERT INTO esporte Values(57, 'basquete', 'philadelphia X brooklyn');
INSERT INTO esporte Values(58, 'futebol', 'gremio X sao_paulo');
INSERT INTO esporte Values(59, 'basquete', 'new_york X brooklyn');
INSERT INTO esporte Values(60, 'futebol', 'fluminense X palmeiras');
INSERT INTO esporte Values(61, 'futebol', 'sao_paulo X corinthians');
INSERT INTO esporte Values(70, 'futebol', 'sao_paulo X flamengo');
INSERT INTO esporte Values(71, 'futebol', 'fluminense X corinthians');
INSERT INTO esporte Values(72, 'basquete', 'brooklyn X new_york');
INSERT INTO esporte Values(73, 'basquete', 'cleaveland X chicago');
INSERT INTO esporte Values(74, 'futebol', 'fluminense X fluminense');
INSERT INTO esporte Values(75, 'basquete', 'philadelphia X chicago');
INSERT INTO esporte Values(76, 'basquete', 'new_york X chicago');
INSERT INTO esporte Values(77, 'basquete', 'oklahoma X brooklyn');
INSERT INTO esporte Values(78, 'basquete', 'philadelphia X philadelphia');
INSERT INTO esporte Values(79, 'basquete', 'philadelphia X oklahoma');
INSERT INTO esporte Values(80, 'futebol', 'atletico_mineiro X flamengo');
INSERT INTO esporte Values(81, 'basquete', 'new_york X cleaveland');
INSERT INTO esporte Values(82, 'futebol', 'botafogo X botafogo');
INSERT INTO esporte Values(83, 'basquete', 'charlotte X philadelphia');
INSERT INTO esporte Values(84, 'basquete', 'philadelphia X new_york');
INSERT INTO esporte Values(85, 'futebol', 'atletico_mineiro X botafogo');
INSERT INTO esporte Values(86, 'basquete', 'philadelphia X oklahoma');
INSERT INTO esporte Values(87, 'basquete', 'philadelphia X philadelphia');
INSERT INTO peca_teatro Values(20, 'Star Wars: Episode VII - The Force Awakens', 'T', 'Action', 'False', 'J.J. Abrams', '136');
INSERT INTO peca_teatro Values(21, 'Thor: Ragnarok', 'I', 'Action', 'False', 'Taika Waititi', '130');
INSERT INTO peca_teatro Values(22, 'Metropolis', 'I', 'Drama', 'True', 'Fritz Lang', '153');
INSERT INTO peca_teatro Values(23, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'A', 'Comedy', 'False', 'Stanley Kubrick', '95');
INSERT INTO peca_teatro Values(24, 'The Grand Budapest Hotel', 'T', 'Adventure', 'True', 'Wes Anderson', '99');
INSERT INTO peca_teatro Values(41, 'Faa yeung nin wa', 'T', 'Drama', 'True', 'Kar-Wai Wong', '98');
INSERT INTO peca_teatro Values(42, 'Sunrise: A Song of Two Humans', 'A', 'Drama', 'True', 'F.W. Murnau', '94');
INSERT INTO peca_teatro Values(43, 'Cera una volta il West', 'A', 'Western', 'False', 'Sergio Leone', '164');
INSERT INTO peca_teatro Values(44, 'Star Wars', 'L', 'Action', 'False', 'George Lucas', '121');
INSERT INTO peca_teatro Values(45, 'Braveheart', 'W', 'Biography', 'False', 'Mel Gibson', '178');
INSERT INTO peca_teatro Values(46, 'Lawrence of Arabia', 'T', 'Adventure', 'False', 'David Lean', '216');
INSERT INTO peca_teatro Values(47, 'Trainspotting', 'R', 'Drama', 'True', 'Danny Boyle', '94');
INSERT INTO peca_teatro Values(48, 'Pulp Fiction', 'T', 'Crime', 'False', 'Quentin Tarantino', '154');
INSERT INTO peca_teatro Values(51, 'The Grapes of Wrath', 'A', 'Drama', 'False', 'John Ford', '129');
INSERT INTO peca_teatro Values(62, 'Sunrise: A Song of Two Humans', 'A', 'Drama', 'True', 'F.W. Murnau', '94');
INSERT INTO peca_teatro Values(63, 'A Wednesday', 'A', 'Crime', 'True', 'Neeraj Pandey', 'India:104');
INSERT INTO peca_teatro Values(64, 'Psycho', 'A', 'Horror', 'True', 'Alfred Hitchcock', '109');
INSERT INTO peca_teatro Values(65, 'The Bourne Ultimatum', 'J', 'Action', 'False', 'Paul Greengrass', '115');
INSERT INTO peca_teatro Values(66, 'Heat', 'A', 'Action', 'False', 'Michael Mann', '170');
INSERT INTO peca_teatro Values(67, 'Schindlers List', 'I', 'Biography', 'False', 'Steven Spielberg', '195');
INSERT INTO peca_teatro Values(68, 'The Lord of the Rings: The Return of the King', 'G', 'Adventure', 'True', 'Peter Jackson', '201');
INSERT INTO peca_teatro Values(69, 'Munna Bhai M.B.B.S.', 'A', 'Comedy', 'True', 'Rajkumar Hirani', '156');
